# Generated by Django 3.2 on 2022-12-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20221206_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_year',
            field=models.DateField(verbose_name='Год рождения'),
        ),
    ]
